### ISSUE TITLE
interfetele sunt bune, daca ai nevoie sa fie apelate din alte module. Dat fiind ca exercitiul e mic, nu era necesar, dar, cum ziceam poate fi ok in anumite circumstante

### ISSUE THREAD

**Issue by stefanbulzan** [MarkSzilagyi95/fasttrackit-curs10-homework#1]
https://github.com/MarkSzilagyi95/fasttrackit-curs10-homework/blob/b7fae87977a03caf22de6ce5d40101e42ea54439/src/ro/fasttrackit/basket/interfaces/Basket.java#L7

**Comment by MarkSzilagyi95** [comment]
macar asta e bun!
