### ISSUE TITLE
vreau sa stergi toate, nu doar primul element

### ISSUE THREAD

**Issue by stefanbulzan** [MarkSzilagyi95/fasttrackit-curs10-homework#3]
https://github.com/MarkSzilagyi95/fasttrackit-curs10-homework/blob/b7fae87977a03caf22de6ce5d40101e42ea54439/src/ro/fasttrackit/basket/impl/BasketImpl.java#L31

**Comment by MarkSzilagyi95** [comment]
rezolvat
