### ISSUE TITLE
asta e o maare problema ce ai facut aici... Spargi incapsularea, bine deja e sparta... dar e urat de tot... 

### ISSUE THREAD

**Issue by stefanbulzan** [MarkSzilagyi95/fasttrackit-curs10-homework#4]
https://github.com/MarkSzilagyi95/fasttrackit-curs10-homework/blob/b7fae87977a03caf22de6ce5d40101e42ea54439/src/ro/fasttrackit/basket/impl/BasketImpl.java#L59

**Comment by MarkSzilagyi95** [comment]
sper ca acum este rezolvat.
